### ISSUE TITLE
Works well on Dell Inspiron 15 Gaming 7577

### ISSUE THREAD

**Issue by ThatDAMNGuy** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#10]
Hardware ID: HDAUDIO\FUNC_01&VEN_10EC&DEV_0256&SUBSYS_102807FA

Works well on this laptop, you can add support for it if you want to. 
Thanks for the drivers.

![main](https://user-images.githubusercontent.com/13704644/48850399-8cc6d480-ede3-11e8-9162-0a3bd36dc6b1.PNG)

**Comment by ThatDAMNGuy** [comment]
![capture](https://user-images.githubusercontent.com/13704644/48850316-5be69f80-ede3-11e8-862a-5bd7ad8cb7bb.PNG)
![capture2](https://user-images.githubusercontent.com/13704644/48850317-5c7f3600-ede3-11e8-90fa-e5db299935e1.PNG)
![capture3](https://user-images.githubusercontent.com/13704644/48850318-5c7f3600-ede3-11e8-8581-8c426fa60b95.PNG)
![capture4](https://user-images.githubusercontent.com/13704644/48850320-5d17cc80-ede3-11e8-86c3-8793c9be027f.PNG)

**Comment by moriel5** [comment]
It's great that the drivers work well for you, however the project is currently in haitus for noe.
You should take a look at issue #9 for more information.

**Comment by ThatDAMNGuy** [comment]
@moriel5 I know about it, just saw that prior to that.

**Comment by moriel5** [comment]
No problem, sorry if I had bothered you.

**Comment by ThatDAMNGuy** [comment]
It's fine.

**Comment by kevinshroff** [comment]
Thanks for reporting compatibility @ThatDAMNGuy
