### ISSUE TITLE
Add support for XPS 13 9350?

### ISSUE THREAD

**Issue by Pixali** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#2]
I've been trying basically everything I can find to make this darn laptop's audio not sound like complete rubbish or blow my ears out. This seems like the solution, though I can't install it at the moment - the installer returns with "Install Realtek HD Audio Driver Failure !! [Error Code: -0001]"

My hardware ID is INTELAUDIO\FUNC_01&VEN_10EC&DEV_0256&SUBSYS_10280704

I'm happy to do testing etc. if needed.

**Comment by moriel5** [comment]
Are you sure that your laptop has Realtek audio (although Dell generally uses those chips)?

If so, until the KSMRD drivers are compatible with your laptop, try the UAD drivers (these are official drivers, by the way, only for Windows 10 x64).

**Comment by Pixali** [comment]
It absolutely does have realtek audio; I doubt it would've come with realtek drivers or include them on dell's website otherwise. I'll take a look at this UAD thing though when I get a chance.

**Comment by kevinshroff** [comment]
Added support for XPS 13 9350 in latest release KSMRD v3.0.2. Please test & report back, thanks.

**Comment by Pixali** [comment]
Ok, I've successfully installed the new drivers, with no errors or any other issues. All seems to be working just fine, there's no static like with non-realtek drivers, no loud bursts, and the music I've tried so far sounds great! Thanks for your excellent work! :D
