### ISSUE TITLE
dell latitude e7440

### ISSUE THREAD

**Issue by kudotuanminh** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#3]
HDAUDIO\FUNC_01&VEN_10EC&DEV_0292&SUBSYS_102805CB

much appreciated if u can add support for this laptop

**Comment by kevinshroff** [comment]
Hello,
Just added experimental support for the Dell Latitude E7440.

Clone the master branch and install the driver but using files from Modded-KSMRD folder, and try it out.

**Comment by kudotuanminh** [comment]
i tried the driver but it gave me error 0xE000024B

**Comment by kevinshroff** [comment]
Which OS are you trying to install on?

**Comment by kudotuanminh** [comment]
sorry for late reply
i followed the instructions and managed to installed the driver
however. now the driver's giving me problems
when i play music in wmp it gave me sound device problem
and when i unplug my headphones windows will bsod with some realtek .sys driver

**Comment by kevinshroff** [comment]
Okay, that indicates that at a driver level this version of the universal Realtek driver **does not** include driver level support for your device. I'm afraid that my KSMRD driver will not work on your device, unless I rebase it on an older version of the Realtek Driver, which would break support for currently supported devices. I may do a legacy support version of KSMRD in the future, but for now demand seems minimal and I don't have any devices to test it on so this doesn't seem feasible.
