### ISSUE TITLE
headphone/mic input selector not working?

### ISSUE THREAD

**Issue by itsminht** [kevinshroff/KSMRD-Modded-Realtek-Audio-Drivers#5]
Does this feature work with the KSMRD modded drivers? As in, am I able to use the in-line mic on my headsets or earphones when I plug them in?

**Comment by moriel5** [comment]
Why should you not?

What you won't see, unless you explicitly enable it in the settings (I forget what it is called), is the option to select between the internal speakers/microphone and the external ones, meaning that to switch between them, you need to connect/disconnect the external ones.

**Comment by kevinshroff** [comment]
Unfortunately in-line mic's don't work with the combojack - requires having Waves MaxxAudio which is what we're trying to get rid of in the first place. Currently no solution for this, but I might try and tackle it in the future.

**Comment by itsminht** [comment]
Ahh shoot that sucks. Why don't you reach out on reddit or the Dell subreddit for people that are interested in these modded drivers (I'm sure a lot of dell owners are, given how popular your first version was)? Perhaps someone might be able to fix the combojack issue? They could help accelerate the release of these drivers (move out of prerelease stage). Just a suggestion hahah
